### ISSUE TITLE
Mirrored Blockly does not load

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1066]
**Category**

 - Examples

**Component**

Mirrored Blockly

**Describe the bug**

The page errors when attempting to de-reference interpolate args into a block message, causing the whole thing to break.

Also message references aren't being loaded in time.

**To Reproduce**

1. Open the mirror demo.
2. Observe how the blocks aren't placed properly and you can't interact with anything.

**Expected behavior**

You should be able to interact with things. IE no errors.

**Additional context**

```
Uncaught Error: Block "controls_repeat_ext": Message does not reference all 1 arg(s).
    at BlockSvg.module$exports$Blockly$Block.Block.validateTokens_ (blockly_compressed.js:1020:340)
    at BlockSvg.module$exports$Blockly$Block.Block.interpolate_ (blockly_compressed.js:1019:150)
    at BlockSvg.module$exports$Blockly$Block.Block.jsonInit (blockly_compressed.js:1014:448)
    at BlockSvg.init (blockly_compressed.js:87:329)
    at BlockSvg.module$exports$Blockly$Block.Block.doInit_ (blockly_compressed.js:976:339)
    at new BlockSvg (blockly_compressed.js:1075:53)
    at WorkspaceSvg.module$exports$Blockly$WorkspaceSvg.WorkspaceSvg.newBlock (blockly_compressed.js:1200:90)
    at module$contents$Blockly$Xml_domToBlockHeadless (blockly_compressed.js:245:286)
    at $.module$exports$Blockly$Xml.domToBlock (blockly_compressed.js:236:280)
    at VerticalFlyout.module$exports$Blockly$Flyout.Flyout.createFlyoutBlock_ (blockly_compressed.js:1294:292)

```

**Comment by rachel-fenichel** [comment]
Checked 12/12/2022 and it loads and works.
