### ISSUE TITLE
Custom dialogs demo errors when you open the inputs category

### ISSUE THREAD

**Issue by BeksOmega** [rachel-fenichel/blockly-samples#1067]
**Category**

 - Examples

**Component**

The custom dialogs demo

**Describe the bug**

When you open the inputs category, you get an error, causing the demo to break.

Also messages are broken in this one as well.

**To Reproduce**

1. Open the custom dialogs demo.
2. Open the inputs category.
3. Observe the error in the console and how you can't drag blocks from the flyout.

**Expected behavior**

No errors.

Also messages being dereferenced.

**Additional context**

```
field_dropdown.js:397 Uncaught TypeError: Cannot read properties of undefined (reading 'alt')
    at FieldDropdown.$.module$exports$Blockly$FieldDropdown.FieldDropdown.trimOptions_ (field_dropdown.js:397:19)
    at new FieldDropdown (field_dropdown.js:154:10)
    at BlockSvg.init (text.js:487:22)
    at BlockSvg.module$exports$Blockly$Block.Block.doInit_ (block.js:358:14)
    at new BlockSvg (block_svg.js:263:10)
    at WorkspaceSvg.module$exports$Blockly$WorkspaceSvg.WorkspaceSvg.newBlock (workspace_svg.js:1042:12)
    at module$contents$Blockly$Xml_domToBlockHeadless (xml.js:928:21)
    at $.module$exports$Blockly$Xml.domToBlock (xml.js:605:16)
    at VerticalFlyout.module$exports$Blockly$Flyout.Flyout.createFlyoutBlock_ (flyout_base.js:744:17)
    at VerticalFlyout.module$exports$Blockly$Flyout.Flyout.createFlyoutInfo_ (flyout_base.js:658:30)
```

**Comment by gonfunko** [comment]
This has been fixed at some point.
