### ISSUE TITLE
Failed to load workspace from JSON in react

### ISSUE THREAD

**Issue by iamkhan001** [rachel-fenichel/blockly-samples#1232]
Hi There,

I'm facing issue with workspace with react state updates, when ever i try to update state, workspace gets cleared.
Hence to solve this, I'm saving serialized state of workspace and trying to load state when workspace empty. 

below is serialized workspace state 

code:
```
const json = Blockly.serialization.workspaces.save(primaryWorkspace.current);
              
const keys = Object.keys(json);
console.log('keys', keys);

if(keys.length) {
     console.log('save workspace', json);
     setValue('workspace', json)
}
```

state:
```
{
    "blocks": {
        "languageVersion": 0,
        "blocks": [
            {
                "type": "variables_set_dynamic",
                "id": "}Lwn,{ohw[NiQRcw#(_Z",
                "x": 157,
                "y": 140,
                "fields": {
                    "VAR": {
                        "id": "]pL_iWiW_:C+XvNa)Akh"
                    }
                },
                "inputs": {
                    "VALUE": {
                        "block": {
                            "type": "math_number",
                            "id": "+?USD(D_F`QT^xc1J_Zl",
                            "fields": {
                                "NUM": 123
                            }
                        }
                    }
                }
            }
        ]
    },
    "variables": [
        {
            "name": "A",
            "id": "]pL_iWiW_:C+XvNa)Akh",
            "type": "Number"
        }
    ]
}
```

code to load json state:
```
const workspace = getValues('workspace')
if(workspace) {
    console.log('workspace', primaryWorkspace.current);
    console.log('load', workspace);
    Blockly.serialization.workspaces.load(workspace);
}
```

Getting error while loading json into workspace
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getTopBlocks')
    at module$contents$Blockly$serialization$blocks_BlockSerializer.clear (blocks.js:699:1)
    at Object.load (workspaces.js:80:1)
    at BlockyProgram.js:178:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
module$contents$Blockly$serialization$blocks_BlockSerializer.clear @ blocks.js:699
load @ workspaces.js:80
(anonymous) @ BlockyProgram.js:178
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react-dom.development.js:20085 The above error occurred in the <BlocklyComponent> component:
    at BlocklyComponent (http://localhost:3000/static/js/bundle.js:11501:53)
    at BlocklyWorkspaces
```

Please help on this.

**Comment by BeksOmega** [comment]
Hello, What is the value of `primaryWorkspace.current`? Based on the error it looks like `Blockly.serialization.workspaces.load` is expecting a `Workspace` and not receiving one.

**Comment by iamkhan001** [comment]
Hi @BeksOmega 

primaryWorkspace.current returns current workspace as below.

```
WorkspaceSvg {id: '0$hV;~v:Zy6FKn2}tB@+', options: Options, RTL: false, horizontalLayout: false, toolboxPosition: 2, …}MAX_UNDO: 1024RTL: falseaudioManager_: module$exports$Blockly$WorkspaceAudio.WorkspaceAudio {parentWorkspace_: null, SOUNDS_: {…}, lastSound_: null}blockDB_: {}blockDragSurface_: BlockDragSurfaceSvg {SVG_: svg.blocklyBlockDragSurface, dragGroup_: g, container_: div.injectionDiv.geras-renderer.classic-theme, scale_: 1, surfaceXY_: null, …}cachedParentSvgSize_: Size {width: 835, height: 880}cachedParentSvg_: svg.blocklySvgcommentDB_: {}componentManager_: ComponentManager {componentData_: {…}, capabilityToComponentIds_: {…}}connectionChecker: ConnectionChecker {}connectionDBList: (5) [empty, ConnectionDB, ConnectionDB, ConnectionDB, ConnectionDB]currentGesture_: nulldragDeltaXY_: nulldragTargetAreas_: [{…}]flyoutButtonCallbacks_: {}flyout_: nullgetMetrics: ƒ ()grid_: Grid {scale_: 1, gridPattern_: pattern#blocklyGridPattern5307947259772172, spacing_: 0, length_: 1, line1_: line, …}highlightedBlocks_: []horizontalLayout: falseid: "0$hV;~v:Zy6FKn2}tB@+"injectionDiv_: div.injectionDiv.geras-renderer.classic-themeinverseScreenCTMDirty_: trueinverseScreenCTM_: nullisClearing: falseisDragSurfaceActive_: falseisFlyout: falseisMutator: falseisVisible_: truekeyboardAccessibilityMode: falselastRecordedPageScroll_: nulllisteners_: (2) [ƒ, ƒ]markerManager_: MarkerManager {cursor_: Cursor, cursorSvg_: g.blocklyCursor, markers_: {…}, workspace_: WorkspaceSvg, markerSvg_: null}metricsManager_: MetricsManager {workspace_: WorkspaceSvg}oldLeft_: 0oldScale_: 1oldTop_: 0options: Options {RTL: false, oneBasedIndex: true, collapse: true, comments: true, disable: true, …}potentialVariableMap_: nullredoStack_: []rendered: truerenderer_: Renderer {name: 'geras', constants_: ConstantProvider, overrides: null, highlightConstants_: HighlightConstantProvider}resizeHandlerWrapper_: [Array(3)]resizesEnabled_: truescale: 1scrollX: -0scrollY: -0scrollbar: nullsetMetrics: ƒ (a)startScrollX: 0startScrollY: 0svgBackground_: rect.blocklyMainBackgroundsvgBlockCanvas_: g.blocklyBlockCanvassvgBubbleCanvas_: g.blocklyBubbleCanvassvgGroup_: g.blocklyWorkspacetargetWorkspace: nullthemeManager_: ThemeManager {workspace_: WorkspaceSvg, theme_: Theme, subscribedWorkspaces_: Array(2), componentDB_: {…}}toolboxCategoryCallbacks_: {VARIABLE: ƒ, VARIABLE_DYNAMIC: ƒ, PROCEDURE: ƒ}toolboxPosition: 2toolbox_: Toolbox {wouldDelete_: false, workspace_: WorkspaceSvg, id: 'toolbox', toolboxDef_: {…}, horizontalLayout_: false, …}topBlocks_: []topBoundedElements_: []topComments_: []trashcan: nulltypedBlocksDB_: {}undoStack_: []useWorkspaceDragSurface_: truevariableMap_: VariableMap {variableMap_: {…}, workspace: WorkspaceSvg}workspaceDragSurface_: WorkspaceDragSurfaceSvg {SVG_: svg.blocklyWsDragSurface.blocklyOverflowVisible, container_: div.injectionDiv.geras-renderer.classic-theme, previousSibling_: null}[[Prototype]]: module$exports$Blockly$Workspace.Workspace
```
I get saved workspace with this code `const workspace = getValues('workspace') ` 
and i pass workspace json into `Blockly.serialization.workspaces.load(workspace);` 
and it trhows error in this step

**Comment by iamkhan001** [comment]
Issue with loading saved program state is fixed when i pass `primaryWorkspace.current` into load funtion as 
`Blockly.serialization.workspaces.load(workspace, primaryWorkspace.current);`
