### ISSUE TITLE
Slider Field

### ISSUE THREAD

**Issue by anthony-bt** [rachel-fenichel/blockly-samples#1272]
**Category**
 Examples

**Component**
field-slider

**Describe the bug**
Cannot edit the slider

**To Reproduce**

Try to add a parent component with a slider as connected entry. One time you did it, update the value with the slider remembering the original value and affect the same value that originaly. Then, you will see it's no possible to edit the slider field anymore and all others too.

Test in the sandbox here : https://google.github.io/blockly-samples/plugins/field-slider/test/

**Expected behavior**
After editing a value, if it's wrong we could change it always as we wish.

**Comment by gonfunko** [comment]
Thanks for reporting this! I think the issue is actually in core rather than in the slider field; I was able to repro by:

* Drag out two `parent block 50` blocks
* Click the field in the first one to open the slider
* Double click the `parent` portion of the other `parent block 50`
* Click the field of the first one again to re-open the slider
* Double click the `parent` portion of the other one again

Everything will lock up, and along the way the following gets logged to the console:

```
workspace_svg.ts?2d81:2504 Tried to start the same gesture twice.
getGesture @ blockly_compressed.js:1121
deprecation.ts?dcc6:37 Blockly.unbindEvent_ was deprecated in December 2021 and will be deleted in December 2022.
Use Blockly.browserEvents.unbind instead.
warn$$module$build$src$core$utils$deprecation @ blockly_compressed.js:66
field_slider.js:9 Uncaught TypeError: Cannot read properties of undefined (reading '2')
    at unbind$$module$build$src$core$browser_events (blockly_compressed.js:40:245)
    at Object.unbindEvent_$$module$build$src$core$blockly [as unbindEvent_] (blockly_compressed.js:300:56)
    at FieldSlider.dropdownDispose_ (field_slider.js:195:53)
    at hideWithoutAnimation$$module$build$src$core$dropdowndiv (blockly_compressed.js:135:48)
    at WorkspaceSvg$$module$build$src$core$workspace_svg.hideChaff (blockly_compressed.js:1122:244)
    at TouchGesture$$module$build$src$core$touch_gesture.doStart (blockly_compressed.js:825:381)
    at TouchGesture$$module$build$src$core$touch_gesture.doStart (blockly_compressed.js:1012:7)
    at TouchGesture$$module$build$src$core$touch_gesture.handleWsStart (blockly_compressed.js:831:57)
    at WorkspaceSvg$$module$build$src$core$workspace_svg.onMouseDown_ (blockly_compressed.js:1104:161)
    at SVGGElement.g (blockly_compressed.js:37:334)
```

It seems that conditionalBind() is returning an empty array, and that breaks unbind().

**Comment by rachel-fenichel** [comment]
More minimal repro steps:
- Drag in a block with a slider field (here, the `50` block)
- Click on the field to open the slider
- Click away from the field
- Click on the field to open the slider
- Click away from the field
