### ISSUE TITLE
suggested-blocks plugin throws errors

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#1624]
**Category**

 - Plugins

**Component**

suggested-blocks

**Describe the bug**

I've followed the instructions in the README and made sure to `init` the plugin. However, upon startup I get

```
bundle.js:870 Uncaught TypeError: Cannot read properties of undefined (reading 'clearPriorBlockData')
    at BlockSuggestorSerializer.clear (index.js?5df7:230:1)
    at Object.load$$module$build$src$core$serialization$workspaces [as load] (workspaces.ts?95d4:71:1)
    at load (serialization.js?6d62:30:1)
    at eval (index.js?b635:68:1)
    at ./src/index.js (bundle.js:816:1)
    at __webpack_require__ (bundle.js:867:33)
    at bundle.js:1944:37
    at bundle.js:1946:12
```

and if I try to open one of the toolbox categories I get

```
Uncaught TypeError: Couldn't find a callback function when opening a toolbox category.
```

**To Reproduce**

Try to use `@blockly/suggested-blocks` in an application.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by maribethb** [comment]
Weirdly enough, I can't reproduce the errors shown above anymore. But there's still a problem if you initialize the plugin after the workspace is created, which is pretty likely outside of the convoluted playground creation process in plugins, so I'm working on that.

I'm not sure why I can't reproduce this right now, but I think you can have problems because the plugin registers a serializer as a side effect of loading the module. If you then try to deserialize any workspace data before you've initialized the plugin (as I did in my testing, where I initialized all my plugins after the initial data has been loaded), then you would get the errors shown above. So I'm going to add some additional guards against this.

Another scenario is that you register this plugin in only one workspace, but since the serializers are registered globally, you'd get the same error when trying to save/load a workspace this plugin isn't registered for.
