### ISSUE TITLE
create-package with typescript fails due to typescript version

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-samples#1669]
**Category**
 - Plugins

**Component**

create-package

**Describe the bug**

`npx @blockly/create-package plugin horizontal-flyout --type plugin --typescript` failed during the installation step for me due to using a too-recent version of Typescript.

`install` worked fine when I changed the version of Typescript in my new `package.json` to `"^4.3.2"`, matching what `dev-scripts` uses. It failed with version `5.0.4`. This is probably an issue in the template.

**Additional context**
Stack trace:
```
fenichel@fenichel-glaptop2:~/Documents/blockly-samples/plugins$ npx @blockly/create-package plugin horizontal-flyout --type plugin --typescript
Creating a new Blockly plugin with name horizontal-flyout in /home/fenichel/Documents/blockly-samples/plugins/horizontal-flyout.

Installing packages. This might take a couple of minutes.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @blockly/dev-scripts@1.2.32
npm ERR! Found: typescript@5.0.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^5.0.4" from the root project
npm ERR!   peer typescript@"*" from ts-loader@9.4.2
npm ERR!   node_modules/ts-loader
npm ERR!     ts-loader@"^9.4.1" from @blockly/dev-scripts@1.2.32
npm ERR!     node_modules/@blockly/dev-scripts
npm ERR!       dev @blockly/dev-scripts@"^1.2.32" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^4.3.2" from @blockly/dev-scripts@1.2.32
npm ERR! node_modules/@blockly/dev-scripts
npm ERR!   dev @blockly/dev-scripts@"^1.2.32" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^4.3.2" from @blockly/dev-scripts@1.2.32
npm ERR!   node_modules/@blockly/dev-scripts
npm ERR!     dev @blockly/dev-scripts@"^1.2.32" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/fenichel/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fenichel/.npm/_logs/2023-04-17T17_38_01_996Z-debug-0.log
node:child_process:915
    throw err;
    ^

Error: Command failed: cd horizontal-flyout && npm install
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at exports.createPlugin (/home/fenichel/.npm/_npx/cff5129890bdc14b/node_modules/@blockly/create-package/bin/plugin.js:186:5)
    at Command.<anonymous> (/home/fenichel/.npm/_npx/cff5129890bdc14b/node_modules/@blockly/create-package/bin/create.js:40:7)
    at Command.listener [as _actionHandler] (/home/fenichel/.npm/_npx/cff5129890bdc14b/node_modules/commander/lib/command.js:482:17)
    at /home/fenichel/.npm/_npx/cff5129890bdc14b/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/home/fenichel/.npm/_npx/cff5129890bdc14b/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/home/fenichel/.npm/_npx/cff5129890bdc14b/node_modules/commander/lib/command.js:1283:27)
    at /home/fenichel/.npm/_npx/cff5129890bdc14b/node_modules/commander/lib/command.js:1081:27 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 82238,
  stdout: null,
  stderr: null
}
```

**Comment by maribethb** [comment]
Right now dev-create always uses the latest version of TypeScript, which is too advanced for the related tools in dev-scripts. We should have it match what dev-scripts uses.

**Comment by maribethb** [comment]
This is fixed now because dev-scripts was updated to allow ts 5. I think that's a better solution than trying to pin the ts version to that of dev-scripts. We need to be keeping dev-scripts up to date so that latest ts is compatible.
