### ISSUE TITLE
block comments in advanced playground broken

### ISSUE THREAD

**Issue by maribethb** [rachel-fenichel/blockly-samples#2359]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

try to load a plugin with a block comment in the saved data and observe error

### Reproduction steps

1. open the advanced playground
2. drag a block onto the workspace
3. add a comment  to the block via context menu
4. reload page
5. observe error in console

### Stack trace

```shell
index.js:238 Failed to auto import. TypeError: Cannot read properties of undefined (reading 'getBubbleSize')
    at blockToDom$$module$build$src$core$xml (xml.ts:219:26)
    at blockToDomWithXY$$module$build$src$core$xml (xml.ts:131:19)
    at new BlockCreate$$module$build$src$core$events$events_block_create (events_block_create.ts:53:20)
    at appendInternal$$module$build$src$core$serialization$blocks (blocks.ts:429:21)
    at append$$module$build$src$core$serialization$blocks (blocks.ts:378:17)
    at BlockSerializer$$module$build$src$core$serialization$blocks.load (blocks.ts:818:7)
    at Object.load$$module$build$src$core$serialization$workspaces [as load] (workspaces.ts:81:38)
    at updateEditor (index.js:233:1)
    at gui.disableResize (index.js:372:1)
    at addGUIControls (options.js:90:1)
```

**Comment by BeksOmega** [comment]
I can reproduce this, but if I link to my local version of Blockly  to add some logging it no longer reproduces.

```
npm link blockly @blockly/dev-scripts @blockly/dev-tools --force
```

[Edit: also cannot reproduce in core]

**Comment by BeksOmega** [comment]
I'm wondering if this is actually a multiple blocklies problem where the `instanceof` check is failing: https://github.com/google/blockly/blob/049993405e23cf4bf05943eb0d5070116715db2c/core/block.ts#L2403

**Comment by BeksOmega** [comment]
We agree that it's probably a multiple blocklies thing.
