### ISSUE TITLE
HSV slider field JavaScript generator doesn't work

### ISSUE THREAD

**Issue by morghipala** [rachel-fenichel/blockly-samples#2423]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

field colour hsv sliders

### Description

When my tool tries to generate Javascript code for the field i get this error:

`Uncaught TypeError: Cannot read properties of null (reading 'replace')
    at JavascriptGenerator$$module$build$src$generators$javascript$javascript_generator.quote_ (javascript_generator.ts:226:8)
    at javascript.javascriptGenerator.forBlock.pen_color (customActions.js:132:36)
    at JavascriptGenerator$$module$build$src$generators$javascript$javascript_generator.blockToCode (i_ast_node_location.ts:1:1)
    at JavascriptGenerator$$module$build$src$generators$javascript$javascript_generator.workspaceToCode (i_ast_node_location.ts:1:1)
    at script.js:16:45`

I really don't know how to fix it and i need to use this plugin

### Reproduction steps

1. Imprt the plugin (in that case from jsdelivr)
2. Make a custom block following the guide
3. The error appears in `generator.quote_`

### Stack trace

```shell
Uncaught TypeError: Cannot read properties of null (reading 'replace')
    at JavascriptGenerator$$module$build$src$generators$javascript$javascript_generator.quote_ (javascript_generator.ts:226:8)
    at javascript.javascriptGenerator.forBlock.pen_color (customActions.js:132:36)
    at JavascriptGenerator$$module$build$src$generators$javascript$javascript_generator.blockToCode (i_ast_node_location.ts:1:1)
    at JavascriptGenerator$$module$build$src$generators$javascript$javascript_generator.workspaceToCode (i_ast_node_location.ts:1:1)
    at script.js:16:45
```

**Comment by cpcallen** [comment]
> ```
> Uncaught TypeError: Cannot read properties of null (reading 'replace')
>     at JavascriptGenerator$$module$build$src$generators$javascript$javascript_generator.quote_ (javascript_generator.ts:226:8)
> ```

This indicates that `quote_` was incorrectly passed `null` instead of a string.  The next stack frame is:

> ```
>    at javascript.javascriptGenerator.forBlock.pen_color (customActions.js:132:36)
> ```

indicating that it has been called from the custom generator function for you `pen_color` block.

This _suggests_ that the bug might be in your code rather than the plugin, but unfortunately without seeing the code in question it's hard to know for sure.

We'd be more than happy to help you get to the bottom of this, but normally we provide developer support in the [Blockly forum](https://groups.google.com/g/blockly) rather than here in the bug tracker.  Would you be so kind as to post a question there, including the stack trace and the source code for your custom generator function?

I'm going to close this issue for now, but will reopen it if it turns out there really is a problem with the plugin.
